FROM node:8 as build
WORKDIR /build
COPY . .
RUN npm install
RUN npm run build

FROM node:12-alpine as serve
WORKDIR /opt/app
COPY package.json package-lock.json* .env* ./
COPY --from=build /build/dist ./dist
RUN npm install --only=prod
EXPOSE 3005
CMD [ "node", "dist/app.js" ]