defaults: &defaults
  working_directory: ~/rating-service
  docker:
    - image: cyber4all/circleci-aws:docker-git
orbs:
  aws-cli: circleci/aws-cli@1.2.1
  docker: circleci/docker@1.4.0
commands:
  install-aws: aws-cli/install
  setup-aws-cli: aws-cli/setup
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image & Unit Test
          command: | 
            docker build -t rating-service:$CIRCLE_SHA1 .
      - run:
          name: Login to docker
          command: docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
      - run:
          name: Publish Image 
          command: |
            docker tag rating-service:$CIRCLE_SHA1 "${DOCKER_USER_ORG}/rating-service:${CIRCLE_SHA1}"
            docker push "${DOCKER_USER_ORG}/rating-service:${CIRCLE_SHA1}"
      - persist_to_workspace: 
          root: ./
          paths: 
              - ./package.json
              - ./deploy.sh

  integration-test:
    <<: *defaults
    steps:
      - attach_workspace: 
          at: ~/rating-service
      - setup_remote_docker
      - run:
          name: Pull Image
          command: docker pull "${DOCKER_USER_ORG}/rating-service:${CIRCLE_SHA1}"
      - run:
          name: Run Integration Test
          command: |
            echo docker run -it rating-service:$CIRCLE_SHA1 npm test

  deploy-production:
    <<: *defaults
    steps:
      - attach_workspace: 
          at: ~/rating-service
      - checkout
      - setup_remote_docker
      - setup-aws-cli:
          aws-access-key-id: AWS_ECS_AccessKey
          aws-region: AWS_REGION_N_VA
          aws-secret-access-key: AWS_ECS_SecretKey
          version: "1"
      - run:
          name: Login to docker
          command: docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
      - run:
          name: Pull Image
          command: docker pull "${DOCKER_USER_ORG}/rating-service:${CIRCLE_SHA1}"
      - run:
          name: Publish Image 
          command: |
            export SEMVER=$(cat ./package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
            docker tag "${DOCKER_USER_ORG}/rating-service:${CIRCLE_SHA1}" "${DOCKER_USER_ORG}/rating-service:${SEMVER}"
            docker push "${DOCKER_USER_ORG}/rating-service:${SEMVER}"
      - run:
          name: Deploy to ECS
          command: |
            export SEMVER=$(cat ./package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
            export DOCKER_IMAGE="${DOCKER_USER_ORG}/rating-service:${SEMVER}"
            chmod +x ./deploy.sh
            sh ./deploy.sh
            
workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          context:
            - DockerHub
          filters:
            branches:
              ignore: /master/
      - integration-test:
          requires:
            - build
          context:
            - DockerHub
          filters:
            branches:
              ignore: /master/

  build-test-and-deploy-production:
    jobs:
      - build:
          context:
            - DockerHub
          filters:
            branches:
              only: /master/
      - integration-test:
          requires:
            - build
          context:
            - DockerHub
          filters:
            branches:
              only: /master/
      - deploy-production:
          requires:
            - integration-test
          context:
            - DockerHub
            - AWS
          filters:
            branches:
              only: /master/
